#!/bin/bash
# =============================================================================
# RecruAI — EC2 Bootstrap Script
# Run this ONCE on a fresh Amazon Linux 2023 EC2 instance to set up the
# deployment environment.  Requires an IAM role with SecretsManager read
# attached to the instance, or you'll inject secrets via environment later.
#
# Usage:
#   chmod +x scripts/setup-ec2.sh
#   sudo ./scripts/setup-ec2.sh
#
# =============================================================================
set -euo pipefail

echo "=== RecruAI EC2 Bootstrap ==="

# ---- 1. System updates & dependencies ----
dnf update -y
# NOTE: no 'curl' here — AL2023 preinstalls curl-minimal which conflicts
# with the full curl package. curl-minimal covers all script needs.
dnf install -y docker git jq

# ---- 2. Start & enable Docker ----
systemctl enable --now docker
usermod -aG docker ec2-user

# ---- 3. Docker Compose v2 + Buildx plugins ----
mkdir -p /usr/local/lib/docker/cli-plugins
curl -sSL "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
  -o /usr/local/lib/docker/cli-plugins/docker-compose
chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
# Buildx is required for `docker compose build` (not shipped with AL2023 docker)
BUILDX_VER="$(curl -sSL https://api.github.com/repos/docker/buildx/releases/latest | jq -r .tag_name)"
curl -sSL "https://github.com/docker/buildx/releases/download/${BUILDX_VER}/buildx-${BUILDX_VER}.linux-amd64" \
  -o /usr/local/lib/docker/cli-plugins/docker-buildx
chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx

# ---- 4. Create deploy directory & clone repo ----
mkdir -p /opt/recruai
cd /opt/recruai

if [ ! -d ".git" ]; then
  git clone https://github.com/MenteE-s/RecruAI.git .
fi

# ---- 3b. Swap file (mandatory on <=2GB boxes: Docker builds + Kafka OOM without it) ----
if [ ! -f /swapfile ]; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
  sysctl vm.swappiness=10
  echo 'vm.swappiness=10' >> /etc/sysctl.conf
fi

# ---- 5. Fail2ban (SSH brute-force protection) ----
dnf install -y fail2ban
cat > /etc/fail2ban/jail.local << 'F2B'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5

[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/secure
maxretry = 3
F2B
systemctl enable --now fail2ban

# ---- 6. Auto security updates ----
dnf install -y dnf-automatic
sed -i 's/apply_updates = no/apply_updates = yes/' /etc/dnf/automatic.conf
systemctl enable --now dnf-automatic.timer

# ---- 7. Disable password auth (key-only SSH) ----
sed -i 's/PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl restart sshd

# ---- 8. Harden sysctl ----
cat >> /etc/sysctl.conf << 'SYSCTL'
# IP spoofing protection
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Ignore ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0

# Ignore source-routed packets
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# Log martian packets
net.ipv4.conf.all.log_martians = 1
SYSCTL
sysctl -p

# ---- 9. Production env file is generated by the GitHub deploy workflow ----
# (backend/.env.production is written from GitHub Secrets on every deploy,
# so there is nothing to copy by hand). Just make sure the template exists:
if [ ! -f "backend/.env.production" ]; then
  echo ">>> backend/.env.production will be created by the first GitHub Actions deploy."
  echo ">>> Make sure these GitHub Secrets exist: EC2_HOST, EC2_SSH_PRIVATE_KEY,"
  echo ">>> RDS_DATABASE_URL, SECRET_KEY, JWT_SECRET_KEY, GROQ_API_KEY, OPENAI_API_KEY, RESEND_API_KEY"
fi

# ---- 10. Firewall (optional, since SG controls this) ----
# Only enable if you want a host-level firewall in addition to SGs:
# dnf install -y iptables-services
# iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
# iptables -A INPUT -p tcp --dport 22 -j ACCEPT
# iptables -A INPUT -p tcp --dport 80 -j ACCEPT
# iptables -A INPUT -p tcp --dport 443 -j ACCEPT
# iptables -A INPUT -j DROP
# service iptables save

echo ""
echo "=== Bootstrap complete! ==="
echo "Next steps:"
echo "  1. Add GitHub Secrets (repo Settings -> Secrets -> Actions):"
echo "     EC2_HOST, EC2_SSH_PRIVATE_KEY, RDS_DATABASE_URL,"
echo "     SECRET_KEY, JWT_SECRET_KEY, GROQ_API_KEY, OPENAI_API_KEY, RESEND_API_KEY"
echo "  2. Point DNS: api.recruai.menteeai.org (A) -> this instance's Elastic IP"
echo "  3. Push to main (or merge a PR) - GitHub Actions deploys automatically:"
echo "     rsync -> env inject -> compose up -> TLS cert -> health check -> db migrate"
