"""add plan field to user

Revision ID: 0833289caacd
Revises: 48b194249f29
Create Date: 2025-11-28 14:44:09.799232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0833289caacd'
down_revision = '48b194249f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=32), nullable=True))

    # Set default plan for existing users
    op.execute("UPDATE users SET plan = 'free' WHERE plan IS NULL")

    # Make column not nullable
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('plan', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
