"""empty message

Revision ID: 0bf7edcc585f
Revises: 987b8564c0f7
Create Date: 2025-12-10 23:39:15.979837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf7edcc585f'
down_revision = '987b8564c0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.alter_column('school',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('educations', schema=None) as batch_op:
        batch_op.alter_column('school',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
