"""Add multi-round interview fields

Revision ID: 326e2b7f8b71
Revises: c5495337288e
Create Date: 2025-12-01 01:59:38.026332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326e2b7f8b71'
down_revision = 'c5495337288e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = inspector.get_columns('interviews')
    existing_columns = [col['name'] for col in columns]
    columns_to_add = [
        ('current_round', sa.Integer(), True),
        ('max_rounds', sa.Integer(), True),
        ('round_status', sa.String(length=20), True),
        ('final_decision', sa.String(length=20), True),
        ('completed_at', sa.DateTime(), True),
        ('analysis_data', sa.Text(), True),
        ('strengths', sa.Text(), True),
        ('improvements', sa.Text(), True),
    ]
    
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        for col_name, col_type, nullable in columns_to_add:
            if col_name not in existing_columns:
                batch_op.add_column(sa.Column(col_name, col_type, nullable=nullable))

    # Handle foreign key constraint issue by setting invalid ai_agent_id references to NULL
    # before recreating the constraint
    op.execute("""
        UPDATE interviews
        SET ai_agent_id = NULL
        WHERE ai_agent_id IS NOT NULL
        AND ai_agent_id NOT IN (SELECT id FROM ai_interview_agents)
    """)

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('interviews_ai_agent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ai_interview_agents', ['ai_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('interviews_ai_agent_id_fkey'), 'ai_agents', ['ai_agent_id'], ['id'])
        batch_op.drop_column('improvements')
        batch_op.drop_column('strengths')
        batch_op.drop_column('analysis_data')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('final_decision')
        batch_op.drop_column('round_status')
        batch_op.drop_column('max_rounds')
        batch_op.drop_column('current_round')

    # ### end Alembic commands ###
