"""Add shareable profiles and analytics models

Revision ID: 4633bf661588
Revises: e799fc70bc94
Create Date: 2025-12-11 01:15:03.175248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4633bf661588'
down_revision = 'e799fc70bc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shareable_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('show_contact_info', sa.Boolean(), nullable=True),
    sa.Column('show_resume', sa.Boolean(), nullable=True),
    sa.Column('show_experience', sa.Boolean(), nullable=True),
    sa.Column('show_education', sa.Boolean(), nullable=True),
    sa.Column('show_skills', sa.Boolean(), nullable=True),
    sa.Column('show_projects', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shareable_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shareable_profiles_slug'), ['slug'], unique=True)

    op.create_table('profile_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['shareable_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_applications_applied_at'))
        batch_op.drop_index(batch_op.f('idx_applications_pipeline_stage'))
        batch_op.drop_index(batch_op.f('idx_applications_post_id'))
        batch_op.drop_index(batch_op.f('idx_applications_user_id'))
        batch_op.drop_index(batch_op.f('idx_applications_user_post'))

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_interviews_organization_id'))
        batch_op.drop_index(batch_op.f('idx_interviews_scheduled_at'))
        batch_op.drop_index(batch_op.f('idx_interviews_status'))
        batch_op.drop_index(batch_op.f('idx_interviews_user_id'))
        batch_op.drop_index(batch_op.f('idx_interviews_user_status'))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_posts_category'))
        batch_op.drop_index(batch_op.f('idx_posts_created_at'))
        batch_op.drop_index(batch_op.f('idx_posts_employment_type'))
        batch_op.drop_index(batch_op.f('idx_posts_org_status'))
        batch_op.drop_index(batch_op.f('idx_posts_organization_id'))
        batch_op.drop_index(batch_op.f('idx_posts_status'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_users_created_at'))
        batch_op.drop_index(batch_op.f('idx_users_email'))
        batch_op.drop_index(batch_op.f('idx_users_organization_id'))
        batch_op.drop_index(batch_op.f('idx_users_role'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_created_at'), [sa.literal_column('created_at DESC')], unique=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_posts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_org_status'), ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_employment_type'), ['employment_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_created_at'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_posts_category'), ['category'], unique=False)

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_interviews_user_status'), ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_interviews_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_interviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_interviews_scheduled_at'), [sa.literal_column('scheduled_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_interviews_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_applications_user_post'), ['user_id', 'post_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_pipeline_stage'), ['pipeline_stage'], unique=False)
        batch_op.create_index(batch_op.f('idx_applications_applied_at'), [sa.literal_column('applied_at DESC')], unique=False)

    op.drop_table('profile_analytics')
    with op.batch_alter_table('shareable_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shareable_profiles_slug'))

    op.drop_table('shareable_profiles')
    # ### end Alembic commands ###
