"""new change

Revision ID: 48e75664236e
Revises: c9e1f2a3b4da
Create Date: 2026-10-06 21:48:32.442580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48e75664236e'
down_revision = 'c9e1f2a3b4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_alerts')
    op.drop_table('resumes')
    op.drop_table('cv_optimizations')
    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_otps_user_id'))

    with op.batch_alter_table('recommendation_agent_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recommendation_agent_embeddings_agent_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_recommendation_agent_embeddings_agent_id'))
        batch_op.create_index(batch_op.f('ix_recommendation_agent_embeddings_agent_id'), ['agent_id'], unique=True)

    with op.batch_alter_table('recommendation_job_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recommendation_job_embeddings_job_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_recommendation_job_embeddings_job_id'))
        batch_op.create_index(batch_op.f('ix_recommendation_job_embeddings_job_id'), ['job_id'], unique=True)

    with op.batch_alter_table('recommendation_profile_embeddings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('recommendation_profile_embeddings_user_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_recommendation_profile_embeddings_user_id'))
        batch_op.create_index(batch_op.f('ix_recommendation_profile_embeddings_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_profile_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_profile_embeddings_user_id'))
        batch_op.create_index(batch_op.f('ix_recommendation_profile_embeddings_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('recommendation_profile_embeddings_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('recommendation_job_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_job_embeddings_job_id'))
        batch_op.create_index(batch_op.f('ix_recommendation_job_embeddings_job_id'), ['job_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('recommendation_job_embeddings_job_id_key'), ['job_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('recommendation_agent_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_agent_embeddings_agent_id'))
        batch_op.create_index(batch_op.f('ix_recommendation_agent_embeddings_agent_id'), ['agent_id'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('recommendation_agent_embeddings_agent_id_key'), ['agent_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_otps_user_id'), ['user_id'], unique=False)

    op.create_table('cv_optimizations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('job_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('optimized_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ats_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keyword_matches', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('suggestions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('cv_optimizations_organization_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cv_optimizations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cv_optimizations_pkey'))
    )
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('template', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('resumes_organization_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('resumes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    op.create_table('job_alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('keywords', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('employment_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('email_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('push_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('job_alerts_organization_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('job_alerts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_alerts_pkey'))
    )
    # ### end Alembic commands ###
