"""Add multi-round interview fields

Revision ID: 4d00317d4f18
Revises: 6255b1ea667c
Create Date: 2025-11-29 16:59:20.622531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d00317d4f18'
down_revision = '6255b1ea667c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_round', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_rounds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('round_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('final_decision', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('analysis_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('improvements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('improvements')
        batch_op.drop_column('strengths')
        batch_op.drop_column('analysis_data')
        batch_op.drop_column('final_decision')
        batch_op.drop_column('round_status')
        batch_op.drop_column('max_rounds')
        batch_op.drop_column('current_round')

    # ### end Alembic commands ###
