"""Add interview completion tracking with completed_at field

Revision ID: 6255b1ea667c
Revises: 54e6251ac903
Create Date: 2025-11-29 16:41:46.981334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6255b1ea667c'
down_revision = '54e6251ac903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First, delete messages with null user_id to avoid constraint violation
    op.execute("DELETE FROM messages WHERE user_id IS NULL")

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('profile_sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_round', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_rounds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('round_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('final_decision', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('analysis_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('strengths', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('improvements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('improvements')
        batch_op.drop_column('strengths')
        batch_op.drop_column('analysis_data')
        batch_op.drop_column('final_decision')
        batch_op.drop_column('round_status')
        batch_op.drop_column('max_rounds')
        batch_op.drop_column('current_round')

    with op.batch_alter_table('profile_sections', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
