"""Add phone, location, website, linkedin fields to User model

Revision ID: 6370b8fe6cd9
Revises: 4633bf661588
Create Date: 2025-12-11 14:29:20.831237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6370b8fe6cd9'
down_revision = '4633bf661588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
