"""Add phone, location, website, linkedin fields to User model

Revision ID: 6370b8fe6cd9
Revises: 4633bf661588
Create Date: 2025-12-11 14:29:20.831237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6370b8fe6cd9'
down_revision = '4633bf661588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_columns = inspector.get_columns('users')
    existing_columns = [col['name'] for col in user_columns]
    
    columns_to_add = [
        ('phone', sa.String(length=50), True),
        ('location', sa.String(length=200), True),
        ('website', sa.String(length=500), True),
        ('linkedin', sa.String(length=500), True),
    ]
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        for col_name, col_type, nullable in columns_to_add:
            if col_name not in existing_columns:
                batch_op.add_column(sa.Column(col_name, col_type, nullable=nullable))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin')
        batch_op.drop_column('website')
        batch_op.drop_column('location')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
