"""add auth fields

Revision ID: 6417d7728a29
Revises: d93ab0edabd0
Create Date: 2025-10-24 01:53:30.458734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6417d7728a29'
down_revision = 'd93ab0edabd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
