"""make password_hash Text to avoid truncation

Revision ID: 77694ecd7e77
Revises: 6417d7728a29
Create Date: 2025-10-24 03:12:39.066128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77694ecd7e77'
down_revision = '6417d7728a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
