"""add Organization model and user role/org_id

Revision ID: 8162e3decd39
Revises: 77694ecd7e77
Create Date: 2025-10-24 14:47:17.201769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8162e3decd39'
down_revision = '77694ecd7e77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        # add role column with a server default so existing rows get a value
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=True, server_default=sa.text("'individual'")))
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['organization_id'], ['id'])

    # ensure existing users have a role set (for older rows)
    op.execute("UPDATE users SET role='individual' WHERE role IS NULL")

    # now remove the server default and enforce NOT NULL at DB level
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role', existing_type=sa.String(length=32), nullable=False, server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('role')

    op.drop_table('organizations')
    # ### end Alembic commands ###
