"""Add subscription fields to User and Organization models, and create TokenUsage table

Revision ID: 91e2c365f98e
Revises: 8c12cfc531b0
Create Date: 2025-12-13 21:11:49.197127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e2c365f98e'
down_revision = '8c12cfc531b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_plan', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('interviews_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tokens_used', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('trial_start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paid_plan', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tokens_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interviews_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('interviews_count')
        batch_op.drop_column('tokens_used')
        batch_op.drop_column('paid_plan')
        batch_op.drop_column('trial_start_date')
        batch_op.drop_column('subscription_status')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('tokens_used')
        batch_op.drop_column('interviews_used')
        batch_op.drop_column('paid_plan')
        batch_op.drop_column('trial_start_date')
        batch_op.drop_column('subscription_status')

    op.drop_table('token_usage')
    # ### end Alembic commands ###
