"""Add timezone field to User and Organization

Revision ID: a42df1ec191c
Revises: 4978e1a66608
Create Date: 2025-12-01 12:31:21.932265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a42df1ec191c'
down_revision = '4978e1a66608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    if inspector.has_table('ai_agents'):
        op.drop_table('ai_agents')
    
    # Check and recreate foreign keys
    conv_fks = inspector.get_foreign_keys('conversation_memories')
    conv_fk_names = [fk['name'] for fk in conv_fks]
    if 'conversation_memories_interview_id_fkey' in conv_fk_names:
        with op.batch_alter_table('conversation_memories', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('conversation_memories_interview_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'interviews', ['interview_id'], ['id'])

    int_fks = inspector.get_foreign_keys('interview_analyses')
    int_fk_names = [fk['name'] for fk in int_fks]
    if 'interview_analyses_interview_id_fkey' in int_fk_names:
        with op.batch_alter_table('interview_analyses', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('interview_analyses_interview_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'interviews', ['interview_id'], ['id'])

    msg_fks = inspector.get_foreign_keys('messages')
    msg_fk_names = [fk['name'] for fk in msg_fks]
    if 'messages_interview_id_fkey' in msg_fk_names:
        with op.batch_alter_table('messages', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('messages_interview_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'interviews', ['interview_id'], ['id'])

    # Check and add timezone to organizations
    org_columns = inspector.get_columns('organizations')
    org_col_names = [col['name'] for col in org_columns]
    if 'timezone' not in org_col_names:
        with op.batch_alter_table('organizations', schema=None) as batch_op:
            batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # Check and add timezone to users
    user_columns = inspector.get_columns('users')
    user_col_names = [col['name'] for col in user_columns]
    if 'timezone' not in user_col_names:
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_interview_id_fkey'), 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('interview_analyses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('interview_analyses_interview_id_fkey'), 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conversation_memories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_memories_interview_id_fkey'), 'interviews', ['interview_id'], ['id'], ondelete='CASCADE')

    op.create_table('ai_agents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('ai_agents_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_agents_pkey'))
    )
    # ### end Alembic commands ###
