"""Add employment status fields to users table

Revision ID: b3acf2c890de
Revises: 9055b793be10
Create Date: 2025-12-14 23:41:49.539240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3acf2c890de'
down_revision = '9055b793be10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_position', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('current_company', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('current_company_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hired_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('onboarded_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['current_company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('onboarded_date')
        batch_op.drop_column('hired_date')
        batch_op.drop_column('current_company_id')
        batch_op.drop_column('current_company')
        batch_op.drop_column('current_position')
        batch_op.drop_column('employment_status')

    # ### end Alembic commands ###
