"""Update Interview model to use AIAgent instead of AIInterviewAgent

Revision ID: c15cbc8c4302
Revises: c84909d3b7c7
Create Date: 2025-11-29 15:10:52.338718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15cbc8c4302'
down_revision = 'c84909d3b7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('interviews_ai_agent_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'ai_agents', ['ai_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('interviews_ai_agent_id_fkey'), 'ai_interview_agents', ['ai_agent_id'], ['id'])

    op.drop_table('ai_agents')
    # ### end Alembic commands ###
