"""Add custom interview platform fields to Interview model

Revision ID: c84909d3b7c7
Revises: 7efbb3eaac80
Create Date: 2025-11-29 13:26:07.065257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84909d3b7c7'
down_revision = '7efbb3eaac80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('room_password', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_column('room_password')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
