"""Add enhanced job posting models with applications and saved jobs

Revision ID: d9de812ceaac
Revises: eaedd24e6339
Create Date: 2025-11-29 10:48:38.658853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9de812ceaac'
down_revision = 'eaedd24e6339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('resume_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('salary_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salary_currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('application_deadline', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('status')
        batch_op.drop_column('application_deadline')
        batch_op.drop_column('requirements')
        batch_op.drop_column('salary_currency')
        batch_op.drop_column('salary_max')
        batch_op.drop_column('salary_min')
        batch_op.drop_column('category')

    op.drop_table('saved_jobs')
    op.drop_table('applications')
    # ### end Alembic commands ###
