"""Add profile and banner images to Organization

Revision ID: f1234567890a
Revises: eaedd24e6339
Create Date: 2025-11-30 07:15:30.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1234567890a'
down_revision = 'eaedd24e6339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('banner_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('banner_image')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###