"""Add onboarded status to applications

Revision ID: f2d98073b6de
Revises: 0bf7edcc585f
Create Date: 2025-12-11 16:56:36.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d98073b6de'
down_revision = '0bf7edcc585f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('onboarded', sa.Boolean(), nullable=True))
    op.execute("UPDATE applications SET onboarded = false")
    op.alter_column('applications', 'onboarded', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'onboarded')
    # ### end Alembic commands ###