"""Add practice AI agent support to interviews

Revision ID: fc7f240956e4
Revises: 3ab6b537de61
Create Date: 2025-12-13 21:51:34.766512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc7f240956e4'
down_revision = '3ab6b537de61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_ai_agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'practice_ai_agents', ['practice_ai_agent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('practice_ai_agent_id')

    # ### end Alembic commands ###
